### ISSUE TITLE
Keywords list

### ISSUE THREAD

**Issue by sarahmoody1** [moj-analytical-services/mojspeakr#12]
Could not remove keywords from list that format words bold in add_summary_table() function.

**Comment by BrydenFrancesca** [comment]
Have you got an example of when you want to remove a keyword from the list?

**Comment by sarahmoody1** [comment]
There is an example [here](https://github.com/moj-analytical-services/MLP-RAP/commit/8ed613e2656c4188976109f3b226b9a068ae1910#commitcomment-49759890) and [this](https://github.com/moj-analytical-services/MLP-RAP/blob/development/sources/timeliness_functions.R#commitcomment-49760163) is a function that relates to the example (timeliness_change function). This function has some words ("up and "down") that we don't want bold and is used inside the add_summary_table() function in the bulletin.
