### ISSUE TITLE
Replication of CTA tag appearance in HTML

### ISSUE THREAD

**Issue by DIPAD-Fran-Bryden** [moj-analytical-services/mojspeakr#21]
Currently, the call to action box tag returns as $CTA in the markdown version of the document, but returns silently in the HTML version.

This is counter to all the other features (e.g. blue header) which return an approximation of the gov.uk appearance in the HTML version.

Suggest adding a HTML return (grey box) for this function

**Comment by BrydenFrancesca** [comment]
Feature added
