### ISSUE TITLE
Could add a code linter

### ISSUE THREAD

**Issue by ms130** [moj-analytical-services/mojspeakr#25]
If that's desired could be run either locally, or automatically upon pull request with GH Actions.

**Comment by BrydenFrancesca** [comment]
I think this is a great idea! I like the lintr package for linting, and in a bit of meta-coding they have a [Github Action](https://github.com/r-lib/lintr/blob/main/.github/workflows/lint-changed-files.yaml) which runs lintr on the updated files in the lintr package which we could steal?
